version: '3'
services:

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./storage/www:/var/www/html
    links:
      - php-fpm

  php-fpm:
    build: ./php-fpm
    volumes:
      - ./storage/www:/var/www/html
    links:
      - redis
      - database

  redis:
    image: redis

  database:
    image: mariadb:10.0.20
    ports:
      - "3306"
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./storage/database:/var/lib/mysql
  