version: '3'
services:

  nginx:
    build: 
      context: .
      dockerfile: containers/nginx/Dockerfile
    ports:
      - "80:80"
      # - "443:443"   # uncomment if you will serve HTTPS
    volumes:
      - ./volumes/www:/var/www/html
    links:
      - php-fpm

  php-fpm:
    build: 
      context: .
      dockerfile: containers/php-fpm/Dockerfile
    volumes:
      - ./volumes/www:/var/www/html
    links:
      - redis
      - database

  redis:
    image: redis:4.0-alpine
    command: redis-server --appendonly yes
    volumes:
      - ./volumes/redis:/data

  database:
    image: mariadb:10.0.20
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./volumes/database:/var/lib/mysql
  